export const mockProductsData = [
    {
        id: 1,
        image: "/assets/images/product_01.png",
        title: "Fan Motor",
        description: "Non OE, Alto K10, Wagon R, Swift KB Series Petrol Engine",
        type: "Full Unit",
        partNumber: "LBP-2037",
        segment: "2 Wheeler",
        brand: "Lispart",
        oem: "Honda",
        rating: 4,
        price: 6237.0,
        oldPrice: 6530.0,
        link: "#",
        isWished: false,
    },
    {
        id: 2,
        image: "/assets/images/product_02.png",
        title: "Brake Pads",
        description: "OE, Maruti Suzuki Swift, Dzire, Baleno",
        type: "Child Part",
        partNumber: "26721344",
        segment: "Passenger Vehicle",
        brand: "Lucas TVS",
        oem: "Kia Motors",
        rating: 5,
        price: 8179.0,
        oldPrice: 8179.0,
        link: "#",
        isWished: true,
    },
    {
        id: 3,
        image: "/assets/images/product_03.png",
        title: "Air Filter",
        description: "Non OE, Hyundai i20, Creta, Verna",
        type: "Full Unit",
        partNumber: "AF-3001",
        segment: "Passenger Vehicle",
        brand: "Bosch",
        oem: "Hyundai",
        rating: 4,
        price: 1200.0,
        oldPrice: 1200.0,
        link: "#",
        isWished: false,
    },
    {
        id: 4,
        image: "/assets/images/product_04.png",
        title: "Oil Filter",
        description: "OE, Honda City, Jazz, Amaze",
        type: "Full Unit",
        partNumber: "OF-4025",
        segment: "Passenger Vehicle",
        brand: "Mann-Filter",
        oem: "Honda",
        rating: 4,
        price: 850.0,
        oldPrice: 1050.0,
        link: "#",
        isWished: true,
    },
    {
        id: 5,
        image: "/assets/images/product_01.png",
        title: "Spark Plug",
        description: "Non OE, Ford Figo, Aspire, EcoSport",
        type: "Child Part",
        partNumber: "SP-1234",
        segment: "Passenger Vehicle",
        brand: "Denso",
        oem: "Ford",
        rating: 5,
        price: 450.0,
        oldPrice: 450.0,
        link: "#",
        isWished: false,
    },
    {
        id: 6,
        image: "/assets/images/product_02.png",
        title: "Clutch Kit",
        description: "OE, Tata Nexon, Harrier, Safari",
        type: "Full Unit",
        partNumber: "CK-4567",
        segment: "Passenger Vehicle",
        brand: "Valeo",
        oem: "Tata",
        rating: 5,
        price: 6500.0,
        oldPrice: 6500.0,
        link: "#",
        isWished: true,
    },
    {
        id: 7,
        image: "/assets/images/product_03.png",
        title: "Headlight Bulb",
        description: "Non OE, Renault Kwid, Duster, Triber",
        type: "Child Part",
        partNumber: "HB-7890",
        segment: "Passenger Vehicle",
        brand: "Philips",
        oem: "Renault",
        rating: 3,
        price: 1200.0,
        oldPrice: 1200.0,
        link: "#",
        isWished: false,
    },
    {
        id: 8,
        image: "/assets/images/product_04.png",
        title: "Brake Disc",
        description: "OE, Toyota Innova, Fortuner, Corolla",
        type: "Full Unit",
        partNumber: "BD-1011",
        segment: "Passenger Vehicle",
        brand: "Brembo",
        oem: "Toyota",
        rating: 4,
        price: 3500.0,
        oldPrice: 3500.0,
        link: "#",
        isWished: true,
    },
    {
        id: 9,
        image: "/assets/images/product_01.png",
        title: "Wiper Blades",
        description: "Non OE, Nissan Micra, Sunny, Terrano",
        type: "Child Part",
        partNumber: "WB-1213",
        segment: "Passenger Vehicle",
        brand: "Bosch",
        oem: "Nissan",
        rating: 4,
        price: 600.0,
        oldPrice: 600.0,
        link: "#",
        isWished: false,
    },
    {
        id: 10,
        image: "/assets/images/product_02.png",
        title: "Battery",
        description: "OE, Mahindra Scorpio, XUV500, Thar",
        type: "Full Unit",
        partNumber: "BT-1415",
        segment: "Passenger Vehicle",
        brand: "Exide",
        oem: "Mahindra",
        rating: 5,
        price: 5500.0,
        oldPrice: 5500.0,
        link: "#",
        isWished: true,
    },
    {
        id: 11,
        image: "/assets/images/product_03.png",
        title: "Fuel Pump",
        description: "Non OE, Volkswagen Polo, Vento, Jetta",
        type: "Full Unit",
        partNumber: "FP-1617",
        segment: "Passenger Vehicle",
        brand: "Bosch",
        oem: "Volkswagen",
        rating: 4,
        price: 28000.0,
        oldPrice: 28000.0,
        link: "#",
        isWished: false,
    },
    {
        id: 12,
        image: "/assets/images/product_04.png",
        title: "Radiator",
        description: "OE, Skoda Rapid, Octavia, Superb",
        type: "Full Unit",
        partNumber: "RD-1819",
        segment: "Passenger Vehicle",
        brand: "Behr",
        oem: "Skoda",
        rating: 5,
        price: 10000.0,
        oldPrice: 10000.0,
        link: "#",
        isWished: true,
    },
];
